import "./globals.css";
import { Inter } from "next/font/google";
import { NextAuthProvider } from "@/providers/NextAuthProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { MaterialUIProvider } from "@/providers/MaterialUIProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Backup Manager",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <NextAuthProvider session={session!}>
      <MaterialUIProvider>
        <html lang="en">
          <head>
            <meta
              name="viewport"
              content="initial-scale=1, width=device-width"
            />
          </head>
          <body className={inter.className}>{children}</body>
        </html>
      </MaterialUIProvider>
    </NextAuthProvider>
  );
}
