version: '3'
services:
  laravel.test:
    image: brayand/backup-manager-backend:latest
    restart: always
    volumes:
      - backend-storage:/app/storage/app
    depends_on:
      - mysql
    command: /docker-start.sh

  mysql:
    image: brayand/backup-manager-mysql:latest
    restart: always
    volumes:
      - 'backend-mysql:/var/lib/mysql'

  frontend-nodejs:
    image: brayand/backup-manager-frontend:latest
    restart: always
    ports:
      - 3001:3000
    depends_on:
      - laravel.test
    command: npm run start

volumes:
  backend-mysql:
  backend-storage:
