version: '3'
services:
  laravel.test:
    image: brayand/backup-manager-backend:$VERSION
    restart: always
    volumes:
      - backend-storage:/app/storage
      - /:/host
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mysql
    command: /docker-start.sh
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:80 || exit 1" ]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 20s

  mysql:
    image: brayand/backup-manager-mysql:$VERSION
    restart: always
    volumes:
      - 'backend-mysql:/var/lib/mysql'

  frontend:
    image: brayand/backup-manager-frontend:$VERSION
    restart: always
    ports:
      - 49160:3000
    depends_on:
      laravel.test:
        condition: service_healthy
    command: npm run start

volumes:
  backend-mysql:
  backend-storage:
