version: '3'
services:
  laravel.test:
    build:
      context: .
      dockerfile: docker/Dockerfile-php8
    image: brayand/backup-manager-backend:latest

  mysql:
    build:
      context: .
      args:
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_DATABASE: ${DB_DATABASE}
      dockerfile: docker/Dockerfile-mysql
    image: brayand/backup-manager-mysql:latest
