version: '3'
services:
  laravel.test:
    build:
      context: .
      dockerfile: docker/Dockerfile-php8
    image: brayand/backup-manager-backend:latest

  mysql:
    build:
      context: .
      dockerfile: docker/Dockerfile-mysql
    image: brayand/backup-manager-mysql:latest
