version: '3'
services:
  laravel.test:
    build:
      context: .
      dockerfile: docker/Dockerfile-php8
    image: brayand/backup-manager-backend:latest

  mysql:
    build:
      context: .
      dockerfile: docker/Dockerfile-mysql
    image: brayand/backup-manager-mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
